src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column]
    private ?string $phone = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Car::class)]
    private Collection $cars;

    #[ORM\OneToMany(mappedBy: 'driver', targetEntity: Ride::class)]
    private Collection $rides;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Rule::class)]
    private Collection $rules;

    public function __construct()
    {
        $this->cars = new ArrayCollection();
        $this->rides = new ArrayCollection();
        $this->rules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    /**
     * @return Collection<int, Car>
     */
    public function getCars(): Collection
    {
        return $this->cars;
    }

    public function addCar(Car $car): self
    {
        if (!$this->cars->contains($car)) {
            $this->cars->add($car);
            $car->setOwner($this);
        }

        return $this;
    }

    public function removeCar(Car $car): self
    {
        if ($this->cars->removeElement($car)) {
            // set the owning side to null (unless already changed)
            if ($car->getOwner() === $this) {
                $car->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ride>
     */
    public function getRides(): Collection
    {
        return $this->rides;
    }

    public function addRide(Ride $ride): self
    {
        if (!$this->rides->contains($ride)) {
            $this->rides->add($ride);
            $ride->setDriver($this);
        }

        return $this;
    }

    public function removeRide(Ride $ride): self
    {
        if ($this->rides->removeElement($ride)) {
            // set the owning side to null (unless already changed)
            if ($ride->getDriver() === $this) {
                $ride->setDriver(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Rule>
     */
    public function getRules(): Collection
    {
        return $this->rules;
    }

    public function addRule(Rule $rule): self
    {
        if (!$this->rules->contains($rule)) {
            $this->rules->add($rule);
            $rule->setAuthor($this);
        }

        return $this;
    }

    public function removeRule(Rule $rule): self
    {
        if ($this->rules->removeElement($rule)) {
            // set the owning side to null (unless already changed)
            if ($rule->getAuthor() === $this) {
                $rule->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Car;


class ProfilController extends AbstractController
{
    #[Route('/profil', name: 'app_profil')]
    public function profil(): Response
    {
        $user = $this->getUser();

        return $this->render('profil/profil.html.twig', [
            'user' => $user, 
        ]);
    }
}

templates/profil/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% if user %}
      <h1 class="mt-5 text-center">Bienvenue sur votre profil, {{ app.user.email }}!</h1>
      <div class="row mt-4">
        <div class="col-md-6">
          <div class="card mb-4">
            <div class="card-header text-center">
              <h2>Vos voitures</h2>
            </div>
            <div class="card-body">
              {% if user.cars is not empty %}
              <table>
                <tbody>
                  {% for car in user.cars %}
                  <tr>
                    <td>{{ car.brand }} {{ car.model }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="{{ path('app_edit', {'id': car.id}) }}" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_car', {'id': car.id}) }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p>Aucune voiture enregistrée.</p>
              {% endif %}
              <a href="{{ path('app_add') }}" class="btn btn-success">Ajouter</a>
              <!-- Bouton Ajouter -->
            </div>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card mb-4">
            <div class="card-header text-center">
              <h2>Vos trajets proposés</h2>
            </div>
            <div class="card-body">
              {% if user.rides is not empty %}
              <table>
                <tbody>
                  {% for ride in user.rides %}
                  <tr>
                    <td>{{ ride.driver.email }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="#" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_ride', {'id': ride.id}) }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% endif %}
            <a href="" class="btn btn-success">Ajouter</a>
              <!-- Bouton Ajouter -->
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-4">
        <div class="card-header text-center">
          <h2>Informations personnelles</h2>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <table>
                <tbody>
                  <tr>
                    <td><strong>Nom:</strong></td>
                    <td>{{ user.lastName }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="#" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_user') }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td><strong>Prénom:</strong></td>
                    <td>{{ user.firstName }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="#" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_user') }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td><strong>Email:</strong></td>
                    <td>{{ user.email }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="#" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_user') }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td><strong>Numéro de téléphone:</strong></td>
                    <td>{{ user.phone }}</td>
                    <td>
                      <div class="btn-group">
                        <a href="#" class="btn btn-primary">Modifier</a>
                        <a href="{{ path('app_delete_user') }}" class="btn btn-danger">Supprimer</a>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <a href="#" class="btn btn-success">Ajouter</a>
          <!-- Bouton Ajouter -->
        </div>
      </div>

      <div class="card mb-4">
        <div class="card-header text-center">
          <h2>Règles pour les déplacements en véhicule</h2>
        </div>
        <div class="card-body">
          {% if user.rules is not empty %}
          <table>
            <tbody>
              {% for rule in user.rules %}
              <tr>
                <td>{{ rule.description }}</td>
                <td>
                  <div class="btn-group">
                    <a href="#" class="btn btn-primary">Modifier</a>
                    <a href="{{ path('app_delete_rule', {'id': rule.id}) }}" class="btn btn-danger">Supprimer</a>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% endif %}
          <a href="#" class="btn btn-success">Ajouter</a>
          <!-- Bouton Ajouter -->
        </div>
      </div>
      {% else %}
      <p>Veuillez vous connecter pour accéder à votre profil.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}